INSERT IGNORE INTO ARTICLE (id, title, body)
VALUES
    (1, 'Lorem Ipsum 1',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel viverra orci. Ut mollis lacinia dolor in mattis. Quisque imperdiet tempor massa, vel blandit sem eleifend nec. Etiam ac mattis lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean ultrices gravida nibh. Sed quis ultricies erat. Maecenas tincidunt dolor id neque suscipit maximus. Morbi dignissim mi tincidunt, semper erat sed, lobortis augue. Fusce et lacus ac magna porttitor volutpat. Morbi blandit euismod nisi, in mollis tortor vehicula at. Donec venenatis nunc scelerisque nulla imperdiet eleifend. Curabitur vehicula diam lorem, efficitur venenatis ante consectetur quis. Etiam sed maximus leo. Quisque a ante eget urna facilisis rhoncus vel id nulla.
Nam facilisis posuere consectetur. Sed id lectus quis risus semper lacinia. Duis consectetur volutpat magna, non auctor nulla vestibulum quis. Maecenas nibh eros, dapibus quis odio quis, pulvinar eleifend sapien. Curabitur in rutrum enim, eget elementum libero. Mauris egestas imperdiet enim et eleifend. Pellentesque ornare scelerisque est, sollicitudin mattis neque facilisis in. Ut imperdiet eleifend enim, sed mollis leo tincidunt at. Suspendisse pellentesque eleifend enim, vel ultricies ligula ornare a. Praesent vitae ornare est, vitae elementum nunc. Nulla ac viverra lorem.
In blandit id odio ornare tincidunt. Aliquam ac fermentum nisl, nec maximus velit. Phasellus sodales tortor risus, at pretium libero commodo in. In eget nunc iaculis massa fringilla malesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur id mi et quam rutrum tempus. Curabitur suscipit rhoncus nisi sit amet gravida. Sed a ligula imperdiet, ultricies risus ut, dignissim tortor. Sed dignissim nibh vel interdum commodo. Vestibulum egestas fringilla odio ut elementum. Aenean commodo augue diam, vel hendrerit quam pellentesque eu. Proin quis nisl id neque pretium volutpat.
Donec nec neque porta, sagittis ipsum eget, vestibulum augue. Sed ut lacus sagittis, suscipit ipsum non, vulputate erat. Vivamus id sem nisl. Nullam mollis non eros ut dapibus. Nullam in lacus ut urna fringilla scelerisque. Integer et varius ante, nec pharetra nibh. Vivamus convallis augue ac metus vehicula vulputate. Ut vel rhoncus lectus. Vivamus blandit tristique cursus. Fusce ac lorem ac dui rutrum tristique. In quis magna a felis vehicula mattis a sed dolor. Cras tellus dui, dictum efficitur ligula sed, dictum suscipit est. Vivamus sodales elit vitae vulputate mattis.
Sed quis ex nisl. Nam in vestibulum mauris. Aliquam sollicitudin erat viverra nisi posuere maximus. Nullam consectetur tortor quam, vitae tristique turpis sollicitudin ac. Suspendisse congue arcu nec venenatis congue. Vivamus quis finibus diam, sed viverra justo. Cras vitae arcu urna. Nunc dignissim orci id commodo pharetra. Nullam pulvinar velit vel justo feugiat, at faucibus enim accumsan. Mauris pellentesque consectetur egestas. Phasellus augue urna, viverra at diam scelerisque, pharetra venenatis magna. Praesent semper risus lobortis odio pulvinar, non tincidunt arcu condimentum. Aenean ex ex, egestas sit amet laoreet eget, iaculis quis neque.
Aliquam ac commodo justo. Cras risus est, cursus nec tristique quis, pretium eu ligula. Suspendisse imperdiet, ex sed efficitur aliquet, turpis felis sagittis orci, a luctus odio augue id velit. Nullam dapibus tempor lorem, a tempor nisl luctus sit amet. Morbi sit amet felis quam. Aenean mollis euismod ultricies. Nunc sed congue orci, sit amet egestas tellus. Praesent at nibh dapibus, volutpat ligula vitae, pulvinar dolor. Aenean ut ipsum faucibus, venenatis turpis eget, rhoncus tortor. Maecenas elementum et sapien lobortis volutpat. Morbi euismod lectus a leo consequat, eget bibendum ex gravida.
Quisque commodo sapien sit amet eros ultricies, ut fringilla nisl congue. Curabitur velit turpis, tempor id feugiat in, condimentum sed est. Curabitur ultrices lacus eu erat consequat, vitae auctor tortor rutrum. In justo tortor, auctor eu consequat quis, pellentesque et purus. Nulla lacus leo, fermentum nec elit at, mollis tincidunt leo. Sed sit amet arcu rutrum, eleifend orci non, placerat nunc. Sed cursus neque nec metus elementum tempor ut sit amet diam. Nulla ut dui commodo, egestas orci quis, maximus turpis. Mauris hendrerit euismod risus vitae ornare. Aenean at lacus scelerisque, tristique augue vitae, convallis nulla. Duis et imperdiet lacus.
Fusce ex ante, viverra ut iaculis sit amet, iaculis non leo. Vivamus fringilla condimentum sapien sed tincidunt. Cras nec placerat elit. Suspendisse efficitur condimentum tristique. Aenean dignissim velit in eros dapibus elementum. Quisque vestibulum quis ipsum vel tempus. Morbi egestas arcu eros, a lobortis dui fermentum ac. Mauris magna nunc, dictum id ex nec, venenatis efficitur sem. In in ante nec nulla tristique luctus. Aliquam arcu neque, scelerisque eget pellentesque vitae, commodo vitae nulla. Vivamus sagittis feugiat ante eget ultricies. Phasellus vulputate aliquet blandit. Donec rutrum vestibulum tincidunt. Donec vel diam nunc. Etiam a odio nunc. Maecenas tortor ante, venenatis eget tristique at, lobortis quis quam.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam fermentum nec sem at placerat. Pellentesque et mollis velit, a laoreet leo. Vestibulum lobortis, odio et fermentum pharetra, odio odio ultricies purus, vitae vestibulum libero purus sed turpis. Aenean venenatis urna non justo mattis, nec dictum eros accumsan. Donec volutpat lorem nec eros tempus, vel varius libero dignissim. Nullam vel mauris pulvinar, scelerisque lacus eget, elementum nibh.
Phasellus luctus nibh suscipit rutrum commodo. Ut finibus blandit nibh, non commodo magna ultrices in. Sed sed risus mi. Aenean pellentesque arcu eget diam pulvinar vehicula. Morbi gravida lacus non nibh mollis fringilla. Integer feugiat diam vitae lectus molestie sagittis. Mauris in accumsan erat. Proin dapibus enim odio, non ultricies enim tristique quis. Suspendisse interdum nec est sit amet vestibulum. Proin ac elementum velit, nec eleifend est. Proin nibh tellus, suscipit ut nisl vel, rhoncus feugiat ante.'),
    (2, 'Lorem Ipsum 2',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
    (3, 'Lorem Ipsum 3',
    STRINGDECODE('Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n\r\nCras dictum eget nisl vel dignissim. Aliquam efficitur ultricies tellus vel posuere. Nam blandit neque vitae neque tincidunt placerat. Nulla facilisi. In malesuada sem a tortor porttitor, et tincidunt nibh tristique. Morbi facilisis, orci nec facilisis fermentum, ipsum quam commodo purus, non dapibus mauris orci eu odio. Suspendisse ornare est sed laoreet sollicitudin. Morbi ut mattis libero. Sed id fringilla ipsum, sit amet convallis neque. Nam vel ex sapien. In hac habitasse platea dictumst. Suspendisse tempor odio nec diam imperdiet pretium. Aliquam a ex nulla. Etiam pulvinar, est sed finibus ultricies, ante eros ullamcorper arcu, et consectetur augue sem eu ipsum. Ut non suscipit sapien, dapibus faucibus augue. Morbi sed turpis erat.
In vitae orci eu enim cursus consectetur. Nulla facilisi. Nullam porttitor, turpis a vehicula bibendum, metus risus molestie metus, vel sodales mauris urna vel est. Integer scelerisque rutrum tortor, at lobortis neque accumsan non. Cras ullamcorper tempor nulla viverra tincidunt. Etiam arcu tellus, posuere et finibus id, posuere at enim. Curabitur id ante in diam mollis cursus. Cras tellus justo, ornare sed dui egestas, mollis pellentesque velit. Nam eget auctor arcu. Vestibulum non nisl et enim auctor iaculis. Donec maximus iaculis tincidunt. Curabitur sit amet felis vel velit molestie ullamcorper. Sed a pulvinar elit.
Phasellus auctor, nisi vitae rhoncus pellentesque, mauris enim vehicula tortor, eu consectetur nisi leo eu enim. Vivamus mi turpis, volutpat vitae auctor nec, consequat a orci. Maecenas eget nunc pretium urna volutpat tincidunt. Proin ullamcorper vestibulum purus non tristique. Phasellus facilisis nibh at quam ullamcorper lacinia. In tristique nisl quis augue suscipit, non feugiat lacus semper. In sit amet maximus lectus, id fringilla dui.
Curabitur et ipsum non nisl suscipit sollicitudin vel vel arcu. Duis aliquet nec tellus in ornare. Nullam nec consequat dolor, quis gravida sem. Donec ipsum nisl, iaculis id orci eu, finibus facilisis est. Maecenas quis quam venenatis, fringilla magna ac, ultrices elit. Nunc volutpat dictum nulla, vitae dapibus nibh viverra at. Quisque dapibus ligula dolor, eget congue arcu sollicitudin vel. Nunc faucibus, odio posuere condimentum tincidunt, metus elit vestibulum magna, non commodo dui diam ac lectus. Mauris at volutpat eros, eu bibendum nulla. Vivamus fringilla ante ac vehicula dictum. Etiam quis tellus at eros tempor varius.
Ut lorem tellus, maximus ut gravida eu, suscipit ullamcorper lorem. In hac habitasse platea dictumst. Morbi commodo maximus urna. Quisque tortor turpis, ornare vel malesuada id, rutrum nec enim. Mauris ullamcorper fringilla dolor, hendrerit bibendum justo pharetra eu. Phasellus varius porta neque, a tincidunt est tristique non. Curabitur vulputate justo eget mollis hendrerit. Proin ac volutpat nunc. Aenean lobortis cursus auctor. Cras id mi ac augue tempus molestie id ut tellus. In sed molestie ex. Sed erat nisl, pretium sit amet placerat ut, congue a nulla.'));