CREATE TABLE IF NOT EXISTS ARTICLE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    body VARCHAR(20000) NOT NULL,
    theme VARCHAR(20) NOT NULL,
    creation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);